spring.application.name=reporta-tu-calle
server.port=8080
spring.data.mongodb.uri=mongodb+srv://arturoosoriom_db_user:Proyecto123@dsosorio.qgwu3gu.mongodb.net/reportatucalle?retryWrites=true&w=majority&appName=DSOsorio
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB